### ISSUE TITLE
How to integrate custom rules with CLI?

### ISSUE THREAD

**Issue by hania-a** [felipebz/zpa-cli#4]
Hi,
I have created some custom rules for ZPA and have installed them on SonarQube, everything is working fine.   My question is how can I get the custom rules to be run by the CLI as well?   
Thank you!

**Comment by felipebz** [comment]
Hi,

Unfortunately, it is not currently possible to run custom rules through the CLI. The CLI only supports the built-in rules. However, adding support for custom rules in the CLI is a feature that I am currently planning to implement in the future.

**Comment by hania-a** [comment]
Hi Felipe,
Thank you for confirming that it is not currently possible. What would be the best way to achieve it in the short term? Could I modify the CLI source to add support for custom rules myself? If so, could you please share some pointers?
Thanks again

**Comment by felipebz** [comment]
This is now available on [v2.0.0](https://github.com/felipebz/zpa-cli/releases/tag/v2.0.0).

The [custom plugin example](https://github.com/felipebz/zpa/tree/3.5.1/plsql-custom-rules) already generates a .jar file that is compatible with ZPA CLI. The only additional step required is to include the file [`src/main/resources/META-INF/extensions.idx`](https://github.com/felipebz/zpa/blob/3.5.1/plsql-custom-rules/src/main/resources/META-INF/extensions.idx), containing the fully qualified name of the class extending CustomPlSqlRulesDefinition.

To use a custom plugin, place the JAR file into the "plugins" folder of the distribution.
